### ISSUE TITLE
ID vs UUID

### ISSUE THREAD

**Issue by PureW** [openchargemap/ocm-system#104]
What is the meaning of and difference between the `id` and `uuid` fields in the return json-data for charging points?

I could not find them described in any documentation.

**Comment by webprofusion-chrisc** [comment]
Hi, Id is the number we use as the OCM reference and is also used elsewhere to link back to that POI (connection info, user comments etc). UUID is a generated GUID and is only present because when the database was first designed someone commented that we should have one and that it would help them with their integrations. That was nearly 7 years ago! So we don't use the UUID internally, it's just there if you need an alternative ID in your systems.
