### ISSUE TITLE
Add US Campgrounds with Plugs

### ISSUE THREAD

**Issue by Felger** [openchargemap/ocm-system#108]
Two databases that provide campground information with publicly available APIs:
Active: requires you to note data from their API with some logos
http://developer.active.com/docs/read/Campground_APIs

Recreation.gov: This requires you to pull in 50-entry chunks, but covers all national parks and national forests in the US.
https://usda.github.io/RIDB/

For campground plugs, they're typically classified by amperage:

50 amp = nema 14-50 (9.6kW)
30 amp = nema TT-30 (2.9kW)
20 amp = nema 5-20 (1.9kW)
15 amp = nema 5-15 (1.4kW)

This data is useful for planning trips to far-flung locations and finding chargers distant from the nearest fast charger.

**Comment by webprofusion-chrisc** [comment]
Thanks, from a quick look I didn't see an Open Data license on either site. That's ok if they either make the data public domain or specifically grant us permission to relicense that data. Where the license is a bit vague (i.e. they could turn around and claim copyright) we won't be able to touch it.

**Comment by Felger** [comment]
Interestingly, I don't see any mention of a license at all on the RIDB site.  Given the nature of the site, I think it's likely that it's intended to be open, but unless they specifically state that it is, that's a good question.

**Comment by webprofusion-chrisc** [comment]
Closing this for now. OCM aims to provide data specifically for electric vehicle charging infrastructure. Increasingly this means official (dedicated, commercial or gov supported) infrastructure rather than 'opportunity' charging (i.e. using an available electrical supply just because it's there are you can reach it). I think plugshare maps lots of opportunity charging spots already so the information is there if people need to refer to it. Will debate this is a new issue.
