### ISSUE TITLE
New connector needed for Tesla CCS in Europe?

### ISSUE THREAD

**Issue by wattsup-mg** [openchargemap/ocm-system#115]
Superchargers in Europe are having CCS cables added. However, as you'd expect, the CCS is for Tesla vehicles only.
Would it be possible to add 'Tesla CCS' as a connector option to indicate this?

**Comment by webprofusion-chrisc** [comment]
Hmm, so is the connector physically different or does it communicate differently?

**Comment by webprofusion-chrisc** [comment]
Thinking about it, as Tesla is the network operator they are probably the same as any other network with membership. I'm reading that they may possibly open it up to other manufacturers - presumably requiring an app etc to pay/start charging. So unless the connector is physically different or communicates differently then no, it would just be CCS (Type 2) - looking at it we need to tidy up the connector names a bit.

**Comment by wattsup-mg** [comment]
Physically no different so can only assume that there's some authorisation process involved. So... it *might* be opened up.

Interestingly, although there are reports of Model 3 charging on FastNed stations, etc., no M3 has yet been shown at a Tesla site using their CCS.

**Comment by Yoshi1990** [comment]
As I understand it, it's a software lock.  I believe the Type 2 destination chargers have three options;
A dedicated Tesla, All Teslas or All compatible EVs

**Comment by zymurgic** [comment]
I'd suggest that it doens't need another connector type. It's just available to Tesla vehicles with an existing payment contract. Membership required, as such.
Physically, it's just a Type 2 CCS connector.
The issue is that Tesla don't currently detail on their public maps which of their supercharger locations are fitted with these; though I'd guess that the in-car maps for a Model 3 will do.
