### ISSUE TITLE
New data import source - Google Sheet

### ISSUE THREAD

**Issue by chuqtas** [openchargemap/ocm-system#121]
Hi, apologies if this is the wrong forum to be requesting this....

In Australia, we have a couple of large charging networks which are installing DC fast chargers, but they are not part of any network.  One of them currently has 17 out of a total 50 locations, the other one about 14 out of a total of 40 locations.  These organisations do not offer their own data feeds of their locations, and since EV charging is not their primary business (one is a government department, the other is a motoring organisation) I don't expect they are likely to do so.
I've compiled these into a Google Sheet.  I've been in contact with ABetterRoutePlanner admins and they have successfully used this Google Sheet as an auto-imported source of charging locations.  I was hoping that OpenChargeMap might like to do the same.
The Google Sheet is at: https://docs.google.com/spreadsheets/d/1A6jrzPsrrUyWzEQ4HVpoaHK85cK3un0auG1b5Gc85NA/edit#gid=0
There is a bit more context on the second tab of that sheet.
Is this data useful to OCM?  Is an import from here able to be set up?
I have not attached a license to this data - I am the only contributor to it so far and am happy to make it public domain (or CC0, or whatever license you prefer)

**Comment by webprofusion-chrisc** [comment]
HI, thanks for sharing this. The easiest way for us to accept new locations is via our website add function https://openchargemap.org/site/poi/add and once a listing has been entered there is also a 'Copy Listing' button that help if locations are similar equipment etc.

We do in some case create special automated (repeatable) imports but that tends to be for official sources with hundreds or thousands of listings. Alternatively there is a very similar import template here:
https://github.com/openchargemap/ocm-docs/tree/master/DataImport/ImportTemplate which you could transpose the data into.

At the end of the day the real issue is time, i.e. the time it takes you to enter locations manually or to transpose the data (note that we may have may of these locations already), vs the time it takes someone else to write a custom import.
