### ISSUE TITLE
Should Polar chargers (in UK) also mention Polar Instant?

### ISSUE THREAD

**Issue by hchalkley** [openchargemap/ocm-system#132]
Charge points operated by the BP Chargemaster / Polar network currently state "for Polar Plus subscription members only. " in the OCM description - but AIUI these can also be used with the Polar Instant app - https://polarinstant.com/

The membership-only restriction is misleading information

**Comment by webprofusion-chrisc** [comment]
I'd argue that we should be providing summary text for Polar at the network level rather than individually describing this per location ( the option to describe usage restriction per listing is up to the contributors/editors or the data source).

We (Open Charge Map) don't make batch updates to listings in general but some users may re-use the same text in their edits/submissions and if we import them from the UK NCR then some text may be sourced from there.

**Comment by zymurgic** [comment]
What at first seems simple is far more complicated that it should be.
BP Chargemaster (who run the Polar network) have different eligibility requirements for different locations.
Some of their rapid chargers accept contactless payments, they are retrofitting them on devices that they know how to do that with (their own 'Ultracharger' models), but many of them don't.
Some of the devices on the Polar Plus network map aren't actually on the Polar Plus backend, and are in fact connected to the Charge your Car backend, which confusingly is also run by Chargemaster. These ones accept Polar Plus RFID cards, but not Polar Instant.
Some of the devices on the Charge your Car map are actually Chargeplace Scotland, which Polar Plus RFID cards cannot activate, and Polar Instant members cannot activate either. A different membership is required, either a Chargeplace Scotland, or Charge your Car membership.
Some devices have intermittent network connectivity and cannot be reliably activated by mobile phone app.

Therefore, unfortunately, Chargemaster/Polar/Charge your Car/Chargeplace Scotland - despite all being run by the same parent company, is not one entity, and acceptance of membership or payment options is on a per-device basis, and keeping on top of which is which, and what payment options are available on each device is a tedious manual process. I'll reach out to BP Chargemaster and ask them if they can provide a suitably licenced import, which covers all the payment options, such that we can work on keeping all this as accurate as possible.

**Comment by zymurgic** [comment]
A quick note on my write-up here... Chargeplace Scotland is no longer run on the BP Pulse / Chargemaster network, but is run on a white-label version of the Swarco e-connect backend. BP Pulse have nothing to do with them, aside from being the manufacturer of some of the units on that network.

This is now a moot point, since Polar Instant has itself been deprecated, as has the name Polar Network. BP (The parent company) has rebranded Polar Network as BP Pulse, and you now require a different app if you want to interact with the charge points on that network, the old mobile phone apps no longer work. This new app allows either paid subscription members, or ad-hoc access pay-as-you-go access, but they charge a higher tariff for pay-as-you-go.
And of course, like most mobile phone apps to activate or stop charging sessions, this depends on good network signal, both for the handset and the charge point, so BP Pulse offer their paying members an RFID card.

Suggest this issue should be closed.
