### ISSUE TITLE
Website: make front page and POI browsing sections translatable

### ISSUE THREAD

**Issue by webprofusion-chrisc** [openchargemap/ocm-system#15]
Currently only the POI details page of the website has any translation applied. Extend this so that the homepage text and basic POI browsing is translatable.

**Comment by solarpete** [comment]
Hi Chris, I have made some more translations to the website, however it seems that I still do not understand what is the correct way of working with GitHub for Windows in order to be able to get it to you.

Could you create a simple step by guide how to perform an update to OCM code in GitHub for Windows please?

If you are interested, this time I tried this approach which does not work:
- cloning the "ocm-system repository to your local PC" as written in the DeveloperGuide.docx (I cloned the master branch)
- I made the changes at my PC
- I commited the changes
- I tried to sync local data with server (using Sync icon in the upper right corner of GitHub for Win. application), but I got the following message: "Sync failed to push local changes. It seems you do not have permission to push your changes to the repository."
- If I try to make a Pull request, I am not successful either, because the application says: "The source and destination branches are the same."
![github_problem_01](https://cloud.githubusercontent.com/assets/9208139/9020984/378b57e0-37e1-11e5-97f9-e7a7337576fa.png)

**Comment by webprofusion-chrisc** [comment]
Hi Pete, 
check out: https://guides.github.com/activities/contributing-to-open-source/#contributing

The key step is to fork your own copy, that way when it comes time to submitting the info back into GitHub to begin submitting a Pull Request, it's to a copy that your account own on GitHub, not the master branch. Then you submit the Pull Request via the GitHub web site using your fork as the source.

I'd create a new fork, copy your changes into it (I use WinMerge to check each change and ensure I'm only copying required changes). Them create a new Pull Request against ocm-system on GitHub, I then get to review it and will either merge it completely or pick bits out to merge manually (sometimes Pull Requests are out of date compared to the master branch depending on when their fork was made).

Small changes (single file) can just be pasted into new Issues in GitHub and I can copy the code from them.

**Comment by solarpete** [comment]
Thank you Chris. I applied your way successfully. I figured the reason why
it was not working for me initially: I had an older fork of mine of OCM
that could not be synchronized for some reason. But deleting it and making
a new one fixed the problem.

**Comment by webprofusion-chrisc** [comment]
Closing - browsers do a better job of translation than we can. App still needs translations but website doesn't.
