### ISSUE TITLE
Requests failing if MaxLength is more than 250

### ISSUE THREAD

**Issue by harigadhai** [openchargemap/ocm-system#165]
We are using openchargemap API with the client ID and It was working fine with  maxresults=5000 till last month 
Now it is throwing an error(You must specify an API Key, either in an X-API-Key header or key= query string parameter.).
But working fine with maxresults=250. I couldn't find any updates in your document.

Example:
https://api.openchargemap.io/v3/poi/?output=json&countrycode=US&maxresults=5000&compact=true&verbose=false - **not working**

https://api.openchargemap.io/v3/poi/?output=json&countrycode=US&maxresults=250&compact=true&verbose=false - 
 **working**

**Comment by webprofusion-chrisc** [comment]
Hi, API key as now mandatory for most uses:

https://community.openchargemap.org/t/api-keys-are-now-required/161

This allows us to monitor API usage volumes and communicate with API users if there is a change they need to be aware of.  Get yourself an API key and start using it.

If you are unable to use an API key because you have software distributed to multiple users we can temporarily (1 month) let queries through based on your client id, if you can share what that client id is.

Note that in all cases, API usage must be done carefully (avoiding high volumes of expensive queries) to preserve the service for other users. 

Other alternatives to using the API include cloning the data: https://github.com/openchargemap/ocm-data or running your own API mirror:  https://github.com/openchargemap/ocm-system/tree/master/API/OCM.Net/OCM.API.Worker

**Comment by harigadhai** [comment]
Hi Chris,

Thanks for the details. 
 If I use my client ID for the API key,  it is working fine. Do I need to create a new API key or Can I use client ID as an API key?

**Comment by webprofusion-chrisc** [comment]
Hi, please get a proper API key as future versions of the API will only accept real keys. The objective is to be able to contact you via email is there is anything important API related that we need to alert you to.
