### ISSUE TITLE
Parameters are ignored when embedding map

### ISSUE THREAD

**Issue by ronald** [openchargemap/ocm-system#184]
Hi,

if I want to embed OpenChargeMap as described in https://openchargemap.org/site/develop#api, 
the latitude/longitude parameters are ignored.
The parameter languagecode also seems to have no effect.

https://map.openchargemap.io/?mode=embedded&languagecode=de&longitude=13.408333&latitude=52.518611.#183 
The website just redirects to https://map.openchargemap.io/#/search

Thanks.

**Comment by webprofusion-chrisc** [comment]
Hi, the issue is that your URL has an additional .#183 on the end which is confusing the app page router (angular).

Try:
https://map.openchargemap.io/?mode=embedded&languagecode=de&longitude=13.408333&latitude=52.518611

**Comment by ronald** [comment]
Thanks for pointing that out. Lat/lng is working now.

But languagecode seems to be ignored.
Both of these pages look very similar:
https://map.openchargemap.io/?mode=embedded&languagecode=de&longitude=13.408333&latitude=52.518611
https://map.openchargemap.io/?mode=embedded&languagecode=en&longitude=13.408333&latitude=52.518611

**Comment by webprofusion-chrisc** [comment]
I see, there does seem to be a bug with language selection, I can't get it to change in the app at all. Interestingly, nobody has thought to report that as an issue before.

**Comment by webprofusion-chrisc** [comment]
Ok, that should work now (browser may need to refresh). There was a problem in the settings page to set language but the main issue was that "languagecode" was not an implemented option for the app parameters, so it has been implemented now.

**Comment by ronald** [comment]
Thank you.

There are still some english phrases like in the message which appears immediately: "A maximum of 250 results are returned per search. Zoom in for details."
Can I help translate that?

**Comment by webprofusion-chrisc** [comment]
It's possible if you want to try, you'd need to build the app locally and modify the code: https://github.com/openchargemap/ocm-app

Some parts are easier to make translatable than others but I don't think anyone has submitted any translations for a long time. The translation project is here: https://webtranslateit.com/en/projects/6978-Open-Charge-Map and dates back to a much older version of the app, so not all text is used and some text may be possible to use in the app and have translation we just aren't using in this version yet.

The current version of the app was developed in 2016 and has had mostly minor updates since.

**Comment by ronald** [comment]
I already requested an invitation on WebTranslateIt. Are you still maintaining invitations? The page says:
> WebTranslateIt deactivated an invitation for the project Open Charge Map because it wasn’t accepted in more than 3 months.

**Comment by webprofusion-chrisc** [comment]
For app localisation topics, see the work required/planned at  https://github.com/openchargemap/ocm-app/issues/35
