### ISSUE TITLE
Filtering API results

### ISSUE THREAD

**Issue by jumpjack** [openchargemap/ocm-system#222]
How can I filter response from public API? I only need 3 fields, not 30... It's a band waste!

**Comment by webprofusion-chrisc** [comment]
You can filter API results but you can't select individual fields. If you have advanced requirements we recommend you import the data into your own system and provide your own API.

You can use `verbose=false` to remove null fields and related reference data objects
`https://api.openchargemap.io/v3/poi/?output=json&countrycode=IT&maxresults=10&verbose=false`

You can also use compact=true to remove whitespace formatting:
`https://api.openchargemap.io/v3/poi/?output=json&countrycode=IT&maxresults=10&compact=true&verbose=false`

**Comment by jumpjack** [comment]
No, my idea was to save bandwidth and time by filtering **before** downloading; I am already filtering after downloading, but I would like to improve responsiveness of my page: currently I have to donwload and process 8MB and I added on my page a text saying "please wait 30 seconds".

**Comment by webprofusion-chrisc** [comment]
Sure, why are you downloading the whole country? If you try browsing https://map.openchargemap.io you should find it fairly quick to return results because it is querying within a bounding box.

We are limited in the level of flexibility we can offer in our free API so if you do need to download data for a whole country regularly we would encourage you to periodically download the data set into your own database for querying.

**Comment by jumpjack** [comment]
Because I am not looking for the closest charging point, I am making statistics on whole country (total installed power, number of charging points, new installations per day...)
Is it possibile to query the free API just for "last update date"? This would allow limiting the number of downloads, as I would not download anything if my current local backup is already up to date.

**Comment by jumpjack** [comment]
Thanks, I see that also `createdsince` exists, very interesting.
