### ISSUE TITLE
Translation: reference data should be translated in UI

### ISSUE THREAD

**Issue by webprofusion-chrisc** [openchargemap/ocm-system#44]
Currently we can translate dropdown values etc but we dont then use the translation when the information is displayed in pages such as POI details page etc.

Need way to translate model value in web view and also need to look at app detail view.

**Comment by solarpete** [comment]
I wanted to assist with this, but I do not actually know how. After looking a bit into it I found I am still in the dark as far as to how the non-static parts of pages are generated, which code is responsible, and when is it executed (and even in which language it is written). So in order to do anything I would need some explanation of the basics or at least being pointed to some resources, such as tutorials...

**Comment by webprofusion-chrisc** [comment]
Hi pete, I've partially fixed this for at least the website POI details view, I need to look at doing it for the app as well. I'll check in my change this weekend.

A related job that needs doing is we need to do an audit of all pages and describe which parts have text thats not currently translatable, so that we can work through it systematically.

**Comment by solarpete** [comment]
Hi Chris, perfect, thanks for doing it!

I also understand the need for the systematic work :-) So would something like this work OK for the mapping? (I mean highlighting the not translatable text in the printscreens of the displayed pages:)
![01_main_page](https://cloud.githubusercontent.com/assets/9208139/10438124/f5cc29c6-7131-11e5-9b8c-a099a4d6d7e1.PNG)

If yes, I can continue with other pages. Otherwise, feel free to suggest anything that would make the subsequent work easier.

**Comment by webprofusion-chrisc** [comment]
Hi pete, the screenshot does help, I was hoping for a way to be able to check off the work done. Perhaps if we did this but added each group (page?) as a github issue, so we might have 30 issues overall which can be tagged with translation.

**Comment by webprofusion-chrisc** [comment]
I have also attempted to edit your permissions so you have more complete access to the repositories, so you should now be able to tag issues etc.

**Comment by solarpete** [comment]
OK Chris, I can create issues for everything I find untranslated over the next few days and tag them as well. And thanks for the rights and your trust!

**Comment by solarpete** [comment]
I went through all pages that I remembered (however they still might be some that are shown just during some special circumstances) and created issues for each of them. 

Now we would need a way to mark high/low priority ones and ones that maybe do not need to be translated at all (or last), such as the pages about API, since most developers usually have to understand English anyway.
